{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "enterprise-rag.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "enterprise-rag.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector: {}
    {{- range .Values.networkPolicy.allowedEgressCIDRs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
    {{- end }}
{{- end }}
